//! Thread color palette databases for major embroidery thread brands.
//!
//! Provides lookup by code, name, and nearest-color matching for
//! Madeira Rayon, Isacord Polyester, and Sulky Rayon.

/// Thread brand identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum ThreadBrand {
    MadeiraRayon,
    IsacordPolyester,
    SulkyRayon,
}

/// A single thread color entry from a brand's palette.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ThreadEntry {
    pub brand: ThreadBrand,
    pub code: &'static str,
    pub name: &'static str,
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

/// Find a thread by code within a brand's palette.
pub fn find_by_code(brand: ThreadBrand, code: &str) -> Option<&'static ThreadEntry> {
    let palette = list_brand(brand);
    palette.iter().find(|e| e.code == code)
}

/// Find the nearest thread color by Euclidean distance in RGB space.
pub fn find_nearest_color(brand: ThreadBrand, r: u8, g: u8, b: u8) -> &'static ThreadEntry {
    let palette = list_brand(brand);
    let r = r as i32;
    let g = g as i32;
    let b = b as i32;

    palette
        .iter()
        .min_by_key(|e| {
            let dr = e.r as i32 - r;
            let dg = e.g as i32 - g;
            let db = e.b as i32 - b;
            dr * dr + dg * dg + db * db
        })
        .expect("Thread palette should never be empty")
}

/// Get all thread entries for a brand.
pub fn list_brand(brand: ThreadBrand) -> &'static [ThreadEntry] {
    match brand {
        ThreadBrand::MadeiraRayon => &MADEIRA_RAYON,
        ThreadBrand::IsacordPolyester => &ISACORD,
        ThreadBrand::SulkyRayon => &SULKY_RAYON,
    }
}

// =============================================================================
// Madeira Classic Rayon 40 — representative palette (~80 core colors)
// =============================================================================

static MADEIRA_RAYON: [ThreadEntry; 80] = [
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1000",
        name: "Rayon Black",
        r: 0,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1001",
        name: "White",
        r: 255,
        g: 255,
        b: 255,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1002",
        name: "Cream",
        r: 255,
        g: 253,
        b: 228,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1005",
        name: "Light Yellow",
        r: 255,
        g: 255,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1023",
        name: "Gold",
        r: 255,
        g: 204,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1024",
        name: "Dark Gold",
        r: 204,
        g: 153,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1025",
        name: "Amber",
        r: 255,
        g: 179,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1037",
        name: "Light Orange",
        r: 255,
        g: 165,
        b: 79,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1039",
        name: "Dark Orange",
        r: 255,
        g: 128,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1040",
        name: "Tangerine",
        r: 255,
        g: 102,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1078",
        name: "Light Peach",
        r: 255,
        g: 204,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1108",
        name: "Peach",
        r: 255,
        g: 179,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1147",
        name: "Flesh",
        r: 230,
        g: 179,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1174",
        name: "Light Pink",
        r: 255,
        g: 192,
        b: 203,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1120",
        name: "Pink",
        r: 255,
        g: 128,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1109",
        name: "Hot Pink",
        r: 255,
        g: 51,
        b: 119,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1110",
        name: "Magenta",
        r: 204,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1181",
        name: "Rose",
        r: 204,
        g: 51,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1085",
        name: "Dark Rose",
        r: 153,
        g: 0,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1038",
        name: "Coral",
        r: 255,
        g: 127,
        b: 80,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1148",
        name: "Salmon",
        r: 250,
        g: 128,
        b: 114,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1221",
        name: "Red",
        r: 255,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1281",
        name: "Dark Red",
        r: 179,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1182",
        name: "Burgundy",
        r: 128,
        g: 0,
        b: 32,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1183",
        name: "Wine",
        r: 114,
        g: 0,
        b: 38,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1311",
        name: "Light Lavender",
        r: 204,
        g: 179,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1312",
        name: "Lavender",
        r: 153,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1313",
        name: "Purple",
        r: 128,
        g: 0,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1314",
        name: "Dark Purple",
        r: 76,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1320",
        name: "Violet",
        r: 102,
        g: 51,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1330",
        name: "Deep Violet",
        r: 76,
        g: 0,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1075",
        name: "Light Blue",
        r: 173,
        g: 216,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1076",
        name: "Baby Blue",
        r: 137,
        g: 207,
        b: 240,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1133",
        name: "Sky Blue",
        r: 102,
        g: 178,
        b: 255,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1134",
        name: "Blue",
        r: 0,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1142",
        name: "Royal Blue",
        r: 0,
        g: 51,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1143",
        name: "Dark Blue",
        r: 0,
        g: 0,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1242",
        name: "Navy",
        r: 0,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1132",
        name: "Teal",
        r: 0,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1046",
        name: "Dark Teal",
        r: 0,
        g: 102,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1045",
        name: "Light Aqua",
        r: 102,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1090",
        name: "Aqua",
        r: 0,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1247",
        name: "Turquoise",
        r: 0,
        g: 179,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1248",
        name: "Light Teal",
        r: 51,
        g: 179,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1100",
        name: "Mint",
        r: 153,
        g: 230,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1169",
        name: "Light Green",
        r: 102,
        g: 204,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1170",
        name: "Green",
        r: 0,
        g: 153,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1250",
        name: "Kelly Green",
        r: 0,
        g: 128,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1251",
        name: "Dark Green",
        r: 0,
        g: 102,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1357",
        name: "Forest Green",
        r: 0,
        g: 76,
        b: 38,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1370",
        name: "Hunter Green",
        r: 0,
        g: 76,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1371",
        name: "Olive",
        r: 102,
        g: 102,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1156",
        name: "Dark Olive",
        r: 76,
        g: 76,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1157",
        name: "Lime",
        r: 179,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1106",
        name: "Bright Green",
        r: 0,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1058",
        name: "Khaki",
        r: 179,
        g: 179,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1128",
        name: "Tan",
        r: 204,
        g: 179,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1173",
        name: "Light Brown",
        r: 179,
        g: 128,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1144",
        name: "Brown",
        r: 139,
        g: 90,
        b: 43,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1145",
        name: "Dark Brown",
        r: 102,
        g: 51,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1059",
        name: "Chocolate",
        r: 76,
        g: 38,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1158",
        name: "Rust",
        r: 179,
        g: 71,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1021",
        name: "Copper",
        r: 204,
        g: 102,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1054",
        name: "Light Gray",
        r: 204,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1011",
        name: "Steel Gray",
        r: 153,
        g: 153,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1041",
        name: "Medium Gray",
        r: 128,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1042",
        name: "Dark Gray",
        r: 76,
        g: 76,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1043",
        name: "Charcoal",
        r: 51,
        g: 51,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1060",
        name: "Silver",
        r: 192,
        g: 192,
        b: 192,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1055",
        name: "Ecru",
        r: 230,
        g: 220,
        b: 196,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1082",
        name: "Bone",
        r: 230,
        g: 220,
        b: 205,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1149",
        name: "Mauve",
        r: 179,
        g: 128,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1119",
        name: "Dusty Rose",
        r: 204,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1307",
        name: "Plum",
        r: 128,
        g: 0,
        b: 64,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1309",
        name: "Grape",
        r: 102,
        g: 51,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1380",
        name: "Emerald",
        r: 0,
        g: 153,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1283",
        name: "Scarlet",
        r: 230,
        g: 0,
        b: 38,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1284",
        name: "Cherry",
        r: 204,
        g: 0,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1390",
        name: "Spring Green",
        r: 0,
        g: 204,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::MadeiraRayon,
        code: "1391",
        name: "Fern Green",
        r: 76,
        g: 153,
        b: 76,
    },
];

// =============================================================================
// Isacord Polyester 40 — representative palette (~80 core colors)
// =============================================================================

static ISACORD: [ThreadEntry; 80] = [
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0020",
        name: "Black",
        r: 0,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0010",
        name: "Silky White",
        r: 255,
        g: 255,
        b: 255,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0101",
        name: "Eggshell",
        r: 252,
        g: 248,
        b: 232,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0220",
        name: "Cornsilk",
        r: 255,
        g: 248,
        b: 200,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0310",
        name: "Yellow",
        r: 255,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0506",
        name: "Dark Gold",
        r: 179,
        g: 134,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0700",
        name: "Bright Yellow",
        r: 255,
        g: 210,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0800",
        name: "Golden Rod",
        r: 218,
        g: 165,
        b: 32,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0824",
        name: "Liberty Gold",
        r: 196,
        g: 149,
        b: 21,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0904",
        name: "Spanish Gold",
        r: 170,
        g: 121,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0922",
        name: "Ashley Gold",
        r: 179,
        g: 128,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1010",
        name: "Shrimp Pink",
        r: 255,
        g: 179,
        b: 164,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1030",
        name: "Iced Pink",
        r: 255,
        g: 204,
        b: 217,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1300",
        name: "Red Berry",
        r: 220,
        g: 20,
        b: 60,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1301",
        name: "Paprika",
        r: 193,
        g: 68,
        b: 43,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1305",
        name: "Fox Fire",
        r: 230,
        g: 63,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1310",
        name: "Tangerine",
        r: 255,
        g: 106,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1600",
        name: "Spanish Tile",
        r: 204,
        g: 78,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1700",
        name: "Red",
        r: 230,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1800",
        name: "Wildfire",
        r: 204,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1902",
        name: "Poinsettia",
        r: 176,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1904",
        name: "Cardinal",
        r: 153,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2000",
        name: "Bright Ruby",
        r: 179,
        g: 0,
        b: 45,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2101",
        name: "Country Red",
        r: 155,
        g: 0,
        b: 26,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2113",
        name: "Cranberry",
        r: 128,
        g: 0,
        b: 32,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2220",
        name: "Burgundy",
        r: 102,
        g: 0,
        b: 34,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2300",
        name: "Bright Pink",
        r: 255,
        g: 102,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2500",
        name: "Raspberry",
        r: 204,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2504",
        name: "Magenta",
        r: 179,
        g: 0,
        b: 89,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2600",
        name: "Dusty Grape",
        r: 128,
        g: 51,
        b: 89,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2702",
        name: "Grape Jelly",
        r: 102,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2810",
        name: "Orchid",
        r: 179,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2830",
        name: "Heather",
        r: 153,
        g: 102,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2910",
        name: "Purple",
        r: 102,
        g: 0,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2922",
        name: "Dark Purple",
        r: 76,
        g: 0,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3010",
        name: "Lavender",
        r: 179,
        g: 153,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3110",
        name: "Blue Dawn",
        r: 128,
        g: 128,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3210",
        name: "Midnight Blue",
        r: 25,
        g: 25,
        b: 112,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3323",
        name: "Delft Blue",
        r: 0,
        g: 51,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3510",
        name: "Royal Blue",
        r: 0,
        g: 51,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3522",
        name: "Blue",
        r: 0,
        g: 71,
        b: 171,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3600",
        name: "Nordic Blue",
        r: 0,
        g: 102,
        b: 178,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3710",
        name: "Blue Ribbon",
        r: 0,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3810",
        name: "Laguna",
        r: 51,
        g: 153,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3910",
        name: "Crystal Blue",
        r: 102,
        g: 178,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "3962",
        name: "Light Blue",
        r: 153,
        g: 204,
        b: 255,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4010",
        name: "Caribbean",
        r: 0,
        g: 153,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4032",
        name: "Teal",
        r: 0,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4101",
        name: "Dark Teal",
        r: 0,
        g: 102,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4220",
        name: "Aqua",
        r: 51,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4410",
        name: "Jade",
        r: 0,
        g: 153,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4610",
        name: "Dark Jade",
        r: 0,
        g: 102,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "4625",
        name: "Moss Green",
        r: 51,
        g: 102,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5326",
        name: "Evergreen",
        r: 0,
        g: 76,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5374",
        name: "Forest Green",
        r: 0,
        g: 76,
        b: 38,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5415",
        name: "Irish Green",
        r: 0,
        g: 128,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5510",
        name: "Emerald",
        r: 0,
        g: 153,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5610",
        name: "Bright Green",
        r: 0,
        g: 204,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5722",
        name: "Key Lime",
        r: 153,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5833",
        name: "Lime",
        r: 179,
        g: 230,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5912",
        name: "Light Green",
        r: 144,
        g: 204,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "5934",
        name: "Sage",
        r: 134,
        g: 160,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "6011",
        name: "Olive",
        r: 107,
        g: 107,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0651",
        name: "Toast",
        r: 179,
        g: 153,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0722",
        name: "Autumn Leaf",
        r: 179,
        g: 107,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0853",
        name: "Pecan",
        r: 139,
        g: 90,
        b: 43,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0945",
        name: "Pine Bark",
        r: 102,
        g: 68,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1055",
        name: "Bark",
        r: 76,
        g: 51,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0108",
        name: "Light Gray",
        r: 211,
        g: 211,
        b: 211,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0111",
        name: "Oyster",
        r: 192,
        g: 192,
        b: 185,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0124",
        name: "Fieldstone",
        r: 153,
        g: 153,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0131",
        name: "Smoke",
        r: 128,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0132",
        name: "Dark Charcoal",
        r: 76,
        g: 76,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0142",
        name: "Sterling",
        r: 170,
        g: 169,
        b: 173,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0176",
        name: "Fog",
        r: 204,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1172",
        name: "Burnt Orange",
        r: 204,
        g: 85,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1102",
        name: "Brick",
        r: 179,
        g: 71,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "0660",
        name: "Honey",
        r: 204,
        g: 153,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "2153",
        name: "Dusty Mauve",
        r: 153,
        g: 102,
        b: 119,
    },
    ThreadEntry {
        brand: ThreadBrand::IsacordPolyester,
        code: "1352",
        name: "Salmon",
        r: 250,
        g: 128,
        b: 114,
    },
];

// =============================================================================
// Sulky Rayon 40 — representative palette (~80 core colors)
// =============================================================================

static SULKY_RAYON: [ThreadEntry; 80] = [
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1005",
        name: "Black",
        r: 0,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1001",
        name: "Bright White",
        r: 255,
        g: 255,
        b: 255,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1002",
        name: "Soft White",
        r: 250,
        g: 248,
        b: 240,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1071",
        name: "Off White",
        r: 245,
        g: 240,
        b: 225,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1135",
        name: "Pastel Yellow",
        r: 255,
        g: 255,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1023",
        name: "Yellow",
        r: 255,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1024",
        name: "Goldenrod",
        r: 218,
        g: 165,
        b: 32,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1025",
        name: "Mine Gold",
        r: 179,
        g: 134,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1067",
        name: "Butterfly Gold",
        r: 204,
        g: 170,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1126",
        name: "Tan",
        r: 204,
        g: 179,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1128",
        name: "Dark Ecru",
        r: 194,
        g: 178,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1070",
        name: "Gold",
        r: 255,
        g: 204,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1168",
        name: "Light Peach",
        r: 255,
        g: 218,
        b: 185,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1019",
        name: "Peach",
        r: 255,
        g: 179,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1020",
        name: "Peach",
        r: 255,
        g: 160,
        b: 122,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1259",
        name: "Salmon",
        r: 250,
        g: 128,
        b: 114,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1317",
        name: "Torch Red",
        r: 255,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1147",
        name: "Christmas Red",
        r: 220,
        g: 20,
        b: 20,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1037",
        name: "Light Coral",
        r: 255,
        g: 127,
        b: 80,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1188",
        name: "Rust",
        r: 179,
        g: 71,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1181",
        name: "Rust",
        r: 153,
        g: 51,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1035",
        name: "Dark Burgundy",
        r: 102,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1034",
        name: "Burgundy",
        r: 128,
        g: 0,
        b: 32,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1190",
        name: "Dark Red",
        r: 153,
        g: 0,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1119",
        name: "Dark Rose",
        r: 179,
        g: 51,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1109",
        name: "Hot Pink",
        r: 255,
        g: 51,
        b: 119,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1256",
        name: "Sweet Pink",
        r: 255,
        g: 179,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1108",
        name: "Light Pink",
        r: 255,
        g: 204,
        b: 217,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1255",
        name: "Deep Pink",
        r: 230,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1191",
        name: "Dark Rose",
        r: 204,
        g: 51,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1112",
        name: "Orchid",
        r: 204,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1122",
        name: "Purple",
        r: 128,
        g: 0,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1194",
        name: "Dark Purple",
        r: 76,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1296",
        name: "Hyacinth",
        r: 102,
        g: 51,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1193",
        name: "Lilac",
        r: 179,
        g: 153,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1030",
        name: "Periwinkle",
        r: 153,
        g: 128,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1226",
        name: "Violet",
        r: 76,
        g: 0,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1198",
        name: "Dusty Navy",
        r: 51,
        g: 51,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1042",
        name: "Dark Navy",
        r: 0,
        g: 0,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1197",
        name: "Medium Navy",
        r: 0,
        g: 0,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1076",
        name: "Royal Blue",
        r: 0,
        g: 51,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1535",
        name: "Dark Royal Blue",
        r: 0,
        g: 38,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1143",
        name: "True Blue",
        r: 0,
        g: 102,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1196",
        name: "Blue",
        r: 0,
        g: 128,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1029",
        name: "Slate Blue",
        r: 102,
        g: 128,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1028",
        name: "Baby Blue",
        r: 137,
        g: 207,
        b: 240,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1074",
        name: "Powder Blue",
        r: 176,
        g: 224,
        b: 230,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1095",
        name: "Turquoise",
        r: 0,
        g: 179,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1046",
        name: "Teal",
        r: 0,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1045",
        name: "Dark Teal",
        r: 0,
        g: 102,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1090",
        name: "Aqua",
        r: 51,
        g: 204,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1232",
        name: "Mint",
        r: 153,
        g: 230,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1100",
        name: "Light Green",
        r: 144,
        g: 204,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1049",
        name: "Green",
        r: 0,
        g: 153,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1051",
        name: "Kelly Green",
        r: 0,
        g: 128,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1208",
        name: "Forest Green",
        r: 0,
        g: 76,
        b: 38,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1175",
        name: "Dark Green",
        r: 0,
        g: 76,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1177",
        name: "Avocado",
        r: 76,
        g: 102,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1176",
        name: "Dark Avocado",
        r: 51,
        g: 76,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1510",
        name: "Lime",
        r: 179,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1511",
        name: "Bright Green",
        r: 0,
        g: 230,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1056",
        name: "Medium Gray",
        r: 128,
        g: 128,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1219",
        name: "Light Gray",
        r: 192,
        g: 192,
        b: 192,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1220",
        name: "Charcoal",
        r: 51,
        g: 51,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1234",
        name: "Pewter",
        r: 153,
        g: 153,
        b: 153,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1057",
        name: "Khaki",
        r: 179,
        g: 179,
        b: 128,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1058",
        name: "Tawny Tan",
        r: 179,
        g: 153,
        b: 102,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1170",
        name: "Light Brown",
        r: 179,
        g: 128,
        b: 76,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1129",
        name: "Brown",
        r: 139,
        g: 90,
        b: 43,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1130",
        name: "Dark Brown",
        r: 102,
        g: 51,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1059",
        name: "Dark Tawny Brown",
        r: 76,
        g: 38,
        b: 0,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1173",
        name: "Medium Brown",
        r: 139,
        g: 99,
        b: 49,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1021",
        name: "Maple",
        r: 204,
        g: 102,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1158",
        name: "Copper",
        r: 184,
        g: 115,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1261",
        name: "Pale Peach",
        r: 255,
        g: 229,
        b: 204,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1082",
        name: "Ecru",
        r: 230,
        g: 220,
        b: 196,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1180",
        name: "Brick",
        r: 179,
        g: 71,
        b: 51,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1016",
        name: "Pastel Coral",
        r: 255,
        g: 192,
        b: 179,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1081",
        name: "Bone",
        r: 240,
        g: 230,
        b: 210,
    },
    ThreadEntry {
        brand: ThreadBrand::SulkyRayon,
        code: "1032",
        name: "Medium Purple",
        r: 128,
        g: 51,
        b: 128,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_list_brand_madeira() {
        let palette = list_brand(ThreadBrand::MadeiraRayon);
        assert_eq!(palette.len(), 80);
        // First should be black
        assert_eq!(palette[0].name, "Rayon Black");
    }

    #[test]
    fn test_list_brand_isacord() {
        let palette = list_brand(ThreadBrand::IsacordPolyester);
        assert_eq!(palette.len(), 80);
    }

    #[test]
    fn test_list_brand_sulky() {
        let palette = list_brand(ThreadBrand::SulkyRayon);
        assert_eq!(palette.len(), 80);
    }

    #[test]
    fn test_find_by_code() {
        let entry = find_by_code(ThreadBrand::MadeiraRayon, "1221");
        assert!(entry.is_some());
        assert_eq!(entry.unwrap().name, "Red");
    }

    #[test]
    fn test_find_by_code_not_found() {
        let entry = find_by_code(ThreadBrand::MadeiraRayon, "9999");
        assert!(entry.is_none());
    }

    #[test]
    fn test_find_nearest_color_exact() {
        // Pure red should match a red thread
        let entry = find_nearest_color(ThreadBrand::MadeiraRayon, 255, 0, 0);
        assert_eq!(entry.name, "Red");
    }

    #[test]
    fn test_find_nearest_color_black() {
        let entry = find_nearest_color(ThreadBrand::IsacordPolyester, 0, 0, 0);
        assert_eq!(entry.name, "Black");
    }

    #[test]
    fn test_find_nearest_color_white() {
        let entry = find_nearest_color(ThreadBrand::SulkyRayon, 255, 255, 255);
        assert_eq!(entry.name, "Bright White");
    }

    #[test]
    fn test_no_duplicate_codes_per_brand() {
        let brands = [
            ThreadBrand::MadeiraRayon,
            ThreadBrand::IsacordPolyester,
            ThreadBrand::SulkyRayon,
        ];
        for brand in brands {
            let palette = list_brand(brand);
            let mut seen = std::collections::HashSet::new();
            for entry in palette {
                assert!(
                    seen.insert(entry.code),
                    "Duplicate thread code '{}' found in {:?} (name: '{}')",
                    entry.code,
                    brand,
                    entry.name
                );
            }
        }
    }
}
